version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command:
      - bash
      - -c
      - |
        alembic upgrade head
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=password123
      - DB_NAME=fastapi
      - SECRET_KEY=fa627157dccc0b9603b689b061caf062d8eed747c39679dce8ddf3e76a1208ae
      - ALGORITHM=HS256
      - TOKEN_EXPIRATION_TIME=300

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
